description: The settings of a room
type: object
properties:
  roundTypes:
    description: >-
      What round types and their order that will be used. The values must be one
      of `DESCRIBE_IT`, `SOUND_IT_OUT`, `ONE_WORD_DESCRIPTION`, `ACT_IT_OUT`
    type: array
    items:
      type: string
    example: DESCRIBE_IT
  maxTeams:
    description: How many teams are allowed to be created in a room
    type: integer
    example: 5
  roundTimeInSeconds:
    description: How long should a round last in seconds
    type: integer
    example: 60
  allowSkips:
    description: A setting that allows a participant to skip words they cannot act
    type: boolean
    example: false
  wordsPerPerson:
    description: How many words are participants allowed to add into the word bowl
    type: integer
    example: 3
